### ISSUE TITLE
Calendar: Calendar Event Panel - Calendar Shifting When Clicking

### ISSUE THREAD

**Issue by stephenab-business** [joshlipps26/multiuser-calendar#5]
When clicking on a specific day, if the event of that day is clicked, the whole application shifts to the left. This problem also occurs when clicking the edit button of the event.

![image](https://user-images.githubusercontent.com/57915887/70183296-7ff5e580-16b3-11ea-981d-c6d02dcef3da.png)

![image](https://user-images.githubusercontent.com/57915887/70183361-a287fe80-16b3-11ea-934a-f5bb27643b7e.png)

**Comment by joshlipps26** [comment]
bug only seems consistent with deleting events for each day.
removing bootstrap changes for handling events fixes this problem.
